# Generated by Django 2.0.9 on 2019-05-16 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeConnectedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_user_id', models.CharField(max_length=90)),
                ('stripe_access_token', models.CharField(max_length=90)),
                ('stripe_publishable_key', models.CharField(max_length=90)),
                ('refresh_token', models.CharField(max_length=90)),
                ('scope', models.CharField(max_length=40)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
