# Generated by Django 2.0.9 on 2019-06-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripeservice', '0003_stripesavedpaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesavedpaymentmethod',
            name='last4',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
