# Generated by Django 2.0.9 on 2019-05-13 18:15

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eventtools.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', ckeditor.fields.RichTextField()),
                ('type', models.CharField(choices=[('appearance', 'Appearance'), ('attraction', 'Attraction'), ('class/training', 'Class/Training'), ('concert/performance', 'Concert/Performance'), ('Trip/Retreat', 'Trip/Retreat'), ('attraction', 'Attraction'), ('Dinner/Gala', 'Dinner/Gala'), ('Game/Competition', 'Game/Competition'), ('Networking', 'Networking'), ('Tradeshow/Expo', 'Tradeshow/Expo'), ('Tournament', 'Tournament'), ('Seminar', 'Seminar'), ('Race Event', 'Race Event'), ('Other', 'Other')], default='Other', max_length=30)),
                ('category', models.CharField(choices=[('Auto/Boat/Air', 'Auto/Boat/Air'), ('Business/Professional', 'Business/Professional'), ('Charity/Cause', 'Charity/Cause'), ('Community/Culture', 'Community/Culture'), ('Education', 'Education'), ('Fashion/Makeup/Beauty', 'Fashion/Makeup/Beauty'), ('Film/Media', 'Film/Media'), ('Food/Drink', 'Food/Drink'), ('Politics/Government', 'Politics/Government'), ('Health/Wellness', 'Health/Wellness'), ('Hobbies', 'Hobbies'), ('Home/Gardening/Lifestyle', 'Home/Gardening/Lifestyle'), ('School', 'School'), ('Science/Technology/Engineering/Math', 'Science/Technology/Engineering/Math'), ('Seasonal/Holiday', 'Seasonal/Holiday'), ('Sports/Fitness', 'Sports/Fitness'), ('Outdoor/Travel', 'Outdoor/Travel'), ('Other', 'Other')], default='Other', max_length=30)),
                ('location', models.TextField()),
                ('organizers', models.CharField(blank=True, max_length=70, null=True)),
                ('venue', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category_obj', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.Category')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, eventtools.models.OccurrenceMixin),
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventOccurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('repeat', eventtools.models.ChoiceTextField(blank=True, choices=[('RRULE:FREQ=DAILY', 'Daily'), ('RRULE:FREQ=WEEKLY', 'Weekly'), ('RRULE:FREQ=MONTHLY', 'Monthly'), ('RRULE:FREQ=YEARLY', 'Yearly')], default='')),
                ('repeat_until', models.DateField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
            options={
                'ordering': ('start', 'end'),
                'abstract': False,
            },
            bases=(models.Model, eventtools.models.OccurrenceMixin),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='type_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.Type'),
        ),
    ]
