# Generated by Django 2.0.9 on 2019-04-19 23:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import eventtools.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', ckeditor.fields.RichTextField()),
                ('type', models.CharField(choices=[('appearance', 'Appearance'), ('attraction', 'Attraction'), ('class/training', 'Class/Training'), ('concert/performance', 'Concert/Performance'), ('Trip/Retreat', 'Trip/Retreat'), ('attraction', 'Attraction'), ('Dinner/Gala', 'Dinner/Gala'), ('Game/Competition', 'Game/Competition'), ('Networking', 'Networking'), ('Tradeshow/Expo', 'Tradeshow/Expo'), ('Tournament', 'Tournament'), ('Seminar', 'Seminar'), ('Race Event', 'Race Event'), ('other', 'Other')], default='other', max_length=30)),
                ('category', models.CharField(choices=[('auto/boat/air', 'Auto/Boat/Air'), ('business/professional', 'Business/Professional'), ('charity/cause', 'Charity/Cause'), ('community/Culture', 'Community/Culture'), ('other', 'Other')], default='other', max_length=30)),
                ('location', models.TextField()),
                ('venue', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, eventtools.models.OccurrenceMixin),
        ),
        migrations.CreateModel(
            name='EventOccurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('repeat', eventtools.models.ChoiceTextField(blank=True, choices=[('RRULE:FREQ=DAILY', 'Daily'), ('RRULE:FREQ=WEEKLY', 'Weekly'), ('RRULE:FREQ=MONTHLY', 'Monthly'), ('RRULE:FREQ=YEARLY', 'Yearly')], default='')),
                ('repeat_until', models.DateField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
            options={
                'ordering': ('start', 'end'),
                'abstract': False,
            },
            bases=(models.Model, eventtools.models.OccurrenceMixin),
        ),
    ]
