# Generated by Django 2.0.9 on 2019-05-26 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_is_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_active',
            new_name='is_inactive',
        ),
    ]
