# Generated by Django 2.0.9 on 2019-07-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190526_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_inactive',
            field=models.BooleanField(default=False),
        ),
    ]
