# Generated by Django 2.0.9 on 2019-04-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20190422_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='event_occurrence',
        ),
        migrations.AlterField(
            model_name='ticketoption',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
