# Generated by Django 2.0.9 on 2019-04-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='name',
        ),
        migrations.AddField(
            model_name='ticketoption',
            name='name',
            field=models.CharField(default=True, max_length=60),
        ),
    ]
