# Generated by Django 2.0.9 on 2019-04-26 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventoccurrence_creator'),
        ('tickets', '0006_auto_20190425_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketoption',
            name='event_occurrence',
        ),
        migrations.AddField(
            model_name='ticketoption',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
