# Generated by Django 2.0.9 on 2019-04-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20190426_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketoption',
            name='name',
            field=models.CharField(default='Unnamed Ticket', max_length=60),
        ),
    ]
